### ISSUE TITLE
Missing the failure to act... 

### ISSUE THREAD

**Issue by silentoverride** [BlackSnufkin/DeadManSwitch#1]
Firstly, I think your project is great and my follow criticism is only meant in a constructive way. 

There is a fundamental flaw in your application's design. If I read your documentation properly the four modes you've implemented all require a trigger being received by the application to initiate the lock down process, which is more like a Kill Switch rather then a Deadman Switch 

A Deadman Switch works on the principle that it is a failure to act on something that would invoke the system lockdown. In a physical sense a train driver must keep a leaver pushed forward for the train to go, if he has a heart attack and keels over then he is no long able to keep the leaver in place which cuts the power to the engine and applies the emergency breaks.

This could be implemented in software via several ways. Some ideas for thought:
- if an account is not logged into within a certain defined time period (eg, 18h, 3 days etc...)
- a dns text record value cannot be read
- device is not within a define geocached location after x time has passed
- a password isn't inputted into a system alert every x mount of time
- a usb device is missing from udev and cannot be detected or any usb device inserted is detected
- a bluetooth device isn't paired to the laptop within a certian time period
- something like a yubikey isn't triggered every x amount of time.

I wish i could help you code some of these features but my programming skills are quite basic and I lack the skill. I hope i've given you a few ideas to improve your application as it's got the potential to be a killer app if it could do something like above.

**Comment by BlackSnufkin** [comment]
Thanks for your comment. You make a good point.
I got the idea for this app from [BusKill](https://www.buskill.in/).
I'm using their meaning of "dead man's switch" as shown on their website.
I'll still add this feature, but in a different way. 
I'm thinking about having users send a message to the bot once a day at a set time.
If you have more ideas or questions, please let me know.

**Comment by BlackSnufkin** [comment]
Thanks for your comment. You make a good point.
I got the idea for this app from [BusKill](https://www.buskill.in/).
I'm using their meaning of "dead man's switch" as shown on their website.
I'll still add this feature, but in a different way. 
I'm thinking about having users send a message to the bot once a day at a set time.
If you have more ideas or questions, please let me know.

**Comment by BlackSnufkin** [comment]
Now its available
